# Generated by Django 3.1.1 on 2020-11-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_score', models.IntegerField()),
                ('number_of_eagles', models.IntegerField()),
                ('number_of_birdies', models.IntegerField()),
                ('number_of_pars', models.IntegerField()),
                ('number_of_boogies', models.IntegerField()),
                ('number_of_blow_up_holes', models.IntegerField()),
                ('number_of_fairways_hit', models.IntegerField()),
                ('number_of_greens_hit', models.IntegerField()),
                ('memorable_moment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
