# Generated by Django 3.1.1 on 2020-11-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='memorable_moment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_birdies',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_blow_up_holes',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_boogies',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_eagles',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_fairways_hit',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_greens_hit',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_pars',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
