# Generated by Django 3.1.1 on 2020-11-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0002_auto_20201111_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='memorable_moment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_birdies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_blow_up_holes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_boogies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_eagles',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_fairways_hit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_greens_hit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_pars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
