# Generated by Django 3.1.1 on 2020-11-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0003_auto_20201111_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='number_of_birdies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_blow_up_holes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_boogies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_eagles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_fairways_hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_greens_hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_pars',
            field=models.IntegerField(default=0),
        ),
    ]
