# Generated by Django 3.1.1 on 2020-11-12 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0008_auto_20201112_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='golfapp.course'),
            preserve_default=False,
        ),
    ]
