# Generated by Django 3.1.1 on 2020-11-12 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0009_auto_20201112_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='number_of_boogies',
            new_name='number_of_bogeys',
        ),
    ]
