# Generated by Django 3.1.1 on 2020-11-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0011_course_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
    ]
