# Generated by Django 3.1.1 on 2020-11-15 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0015_score_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
    ]
