# Generated by Django 3.1.1 on 2020-11-16 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0021_auto_20201115_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='number_of_blow_up_holes',
        ),
        migrations.RemoveField(
            model_name='score',
            name='number_of_bogeys',
        ),
        migrations.RemoveField(
            model_name='score',
            name='number_of_eagles',
        ),
    ]
