# Generated by Django 3.1.1 on 2020-11-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0022_auto_20201116_0219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ('-date',)},
        ),
    ]
