# Generated by Django 3.1.1 on 2020-11-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0023_auto_20201116_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ('date',)},
        ),
    ]
