# Generated by Django 3.1.1 on 2020-11-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0024_auto_20201117_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ('-date',)},
        ),
    ]
